# Generated by Django 3.2.4 on 2021-07-07 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('numIdentificacion', models.IntegerField(primary_key=True, serialize=False, verbose_name='Número Identificación')),
                ('fotografia', models.ImageField(upload_to='', verbose_name='Fotografía')),
                ('nomCompleto', models.CharField(max_length=50, verbose_name='Nombre Completo')),
                ('telefono', models.IntegerField(verbose_name='Número de telefono')),
                ('direccion', models.CharField(max_length=100, verbose_name='Dirección')),
                ('mail', models.CharField(max_length=100, verbose_name='Correo Electrónico')),
                ('pais', models.CharField(max_length=50, verbose_name='País')),
                ('contraseña', models.CharField(max_length=10, verbose_name='Contraseña')),
                ('monedaPago', models.CharField(max_length=10, verbose_name='Moneda de Pago')),
            ],
        ),
    ]
